# Ruchi Jha
Data Science Bootcamp Week 2 Assignment

**Part 1-Numpy**

Use this dataset for the first 4 questions.

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

1. ⁠Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.

In [56]:
# prompt: Use this dataset for the first 4 questions.
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])⁠.Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.

import numpy as np

# Define two NumPy arrays
A = np.array([[1, 3], [5, 7]])
B = np.array([[4, 5], [6, 7]])

# Stack arrays vertically
vertical_stack = np.vstack((A, B))
print("Vertical Stack:\n", vertical_stack)

# Stack arrays horizontally
horizontal_stack = np.hstack((A, B))
print("\nHorizontal Stack:\n", horizontal_stack)


Vertical Stack:
 [[1 3]
 [5 7]
 [4 5]
 [6 7]]

Horizontal Stack:
 [[1 3 4 5]
 [5 7 6 7]]


2.Find common elements between A and B. [Hint : Intersection of two sets]

In [57]:
import numpy as np
# Convert arrays to sets to find the intersection
setA = set(A.flatten())
setB = set(B.flatten())

common_elements = np.array(list(setA.intersection(setB)))

print("\nCommon elements:\n", common_elements)



Common elements:
 [5 7]


3.Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]

In [58]:
import numpy as np
#Range
min_val = 2
max_val = 6

#np.where() method
indices = np.where((A >= min_val) & (A <= max_val))
numbers_in_range = A[indices]

print("Numbers in range (using np.where):\n", numbers_in_range)


Numbers in range (using np.where):
 [3 5]


4.Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

In [59]:
import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
#filter out selected rows
filtered_iris = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]

filtered_iris

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

**Part 2-PANDAS**


1. ⁠From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [60]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

filtered_df = df.iloc[::20, :]

result = filtered_df[['Manufacturer', 'Model', 'Type']]

print(result)

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


2. Replace missing values in Min.Price and Max.Price columns with their respective mean.

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [61]:
print(df['Min.Price'].isnull().sum())


7


In [62]:
print(df['Max.Price'].isnull().sum())


5


In [63]:
mean_min_price = df['Min.Price'].mean()
mean_max_price = df['Max.Price'].mean()

df['Min.Price'] = df['Min.Price'].fillna(mean_min_price)
df['Max.Price'] = df['Max.Price'].fillna(mean_max_price)

print(df['Min.Price'])
print(df['Max.Price'])

0     12.900000
1     29.200000
2     25.900000
3     17.118605
4     17.118605
        ...    
88    16.600000
89    17.600000
90    22.900000
91    21.800000
92    24.800000
Name: Min.Price, Length: 93, dtype: float64
0     18.800000
1     38.700000
2     32.300000
3     44.600000
4     21.459091
        ...    
88    22.700000
89    22.400000
90    23.700000
91    23.500000
92    28.500000
Name: Max.Price, Length: 93, dtype: float64


In [64]:
print(df['Min.Price'].isnull().sum())


0


In [65]:
print(df['Max.Price'].isnull().sum())


0


3.How to get the rows of a dataframe with row sum > 100?

df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

In [66]:
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
row_sums = df.sum(axis=1)
rows_with_sum_gt_100 = df[row_sums > 100]
rows_with_sum_gt_100


0   1   2   3
3   35  13  33  32
4   20  20  35  35
5   25  22  24  35
7   37  18  37  37
13  27  35  37  17